
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'DoanhThu': typeof import("../components/DoanhThu/doanh-thu.vue")['default']
    'HangNhapDialogCreateDetailHangNhap': typeof import("../components/HangNhap/DialogCreateDetailHangNhap.vue")['default']
    'HangNhapDialogCreateHangNhap': typeof import("../components/HangNhap/DialogCreateHangNhap.vue")['default']
    'HangNhapDialogEditDetailHangNhap': typeof import("../components/HangNhap/DialogEditDetailHangNhap.vue")['default']
    'HangNhapDialogEditHangNhap': typeof import("../components/HangNhap/DialogEditHangNhap.vue")['default']
    'KhachHangDialogCreateDetailKhachHang': typeof import("../components/KhachHang/DialogCreateDetailKhachHang.vue")['default']
    'KhachHangDialogCreateKhachHang': typeof import("../components/KhachHang/DialogCreateKhachHang.vue")['default']
    'KhachHangDialogEditDetailKhachHang': typeof import("../components/KhachHang/DialogEditDetailKhachHang.vue")['default']
    'KhachHangDialogEditKhachHang': typeof import("../components/KhachHang/DialogEditKhachHang.vue")['default']
    'KhachHangDialogShowInfoKhachHang': typeof import("../components/KhachHang/DialogShowInfoKhachHang.vue")['default']
    'KhachHangDialogShowPrintKhachHang': typeof import("../components/KhachHang/DialogShowPrintKhachHang.vue")['default']
    'KhoHangDialogCreateKhoHang': typeof import("../components/KhoHang/DialogCreateKhoHang.vue")['default']
    'KhoHangDialogEditKhoHang': typeof import("../components/KhoHang/DialogEditKhoHang.vue")['default']
    'LoaiHangDialogCreateLoaiHang': typeof import("../components/LoaiHang/DialogCreateLoaiHang.vue")['default']
    'LoaiHangDialogEditLoaiHang': typeof import("../components/LoaiHang/DialogEditLoaiHang.vue")['default']
    'NhanVienDialogCreateKhachHang': typeof import("../components/NhanVien/DialogCreateKhachHang.vue")['default']
    'NhanVienDialogEditKhachHang': typeof import("../components/NhanVien/DialogEditKhachHang.vue")['default']
    'TrangChuTongDuNo': typeof import("../components/TrangChu/TongDuNo.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'MglMap': typeof import("@indoorequal/vue-maplibre-gl")['MglMap']
    'MglAttributionControl': typeof import("@indoorequal/vue-maplibre-gl")['MglAttributionControl']
    'MglCustomControl': typeof import("@indoorequal/vue-maplibre-gl")['MglCustomControl']
    'MglFullscreenControl': typeof import("@indoorequal/vue-maplibre-gl")['MglFullscreenControl']
    'MglGeolocateControl': typeof import("@indoorequal/vue-maplibre-gl")['MglGeolocateControl']
    'MglNavigationControl': typeof import("@indoorequal/vue-maplibre-gl")['MglNavigationControl']
    'MglScaleControl': typeof import("@indoorequal/vue-maplibre-gl")['MglScaleControl']
    'MglLogoControl': typeof import("@indoorequal/vue-maplibre-gl")['MglLogoControl']
    'MglMarker': typeof import("@indoorequal/vue-maplibre-gl")['MglMarker']
    'MglPopup': typeof import("@indoorequal/vue-maplibre-gl")['MglPopup']
    'MglCanvasSource': typeof import("@indoorequal/vue-maplibre-gl")['MglCanvasSource']
    'MglGeoJsonSource': typeof import("@indoorequal/vue-maplibre-gl")['MglGeoJsonSource']
    'MglImageSource': typeof import("@indoorequal/vue-maplibre-gl")['MglImageSource']
    'MglRasterSource': typeof import("@indoorequal/vue-maplibre-gl")['MglRasterSource']
    'MglRasterDemSource': typeof import("@indoorequal/vue-maplibre-gl")['MglRasterDemSource']
    'MglVectorSource': typeof import("@indoorequal/vue-maplibre-gl")['MglVectorSource']
    'MglVideoSource': typeof import("@indoorequal/vue-maplibre-gl")['MglVideoSource']
    'MglBackgroundLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglBackgroundLayer']
    'MglCircleLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglCircleLayer']
    'MglFillLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglFillLayer']
    'MglFillExtrusionLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglFillExtrusionLayer']
    'MglHeatmapLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglHeatmapLayer']
    'MglHillshadeLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglHillshadeLayer']
    'MglLineLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglLineLayer']
    'MglRasterLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglRasterLayer']
    'MglSymbolLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglSymbolLayer']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyDoanhThu': typeof import("../components/DoanhThu/doanh-thu.vue")['default']
    'LazyHangNhapDialogCreateDetailHangNhap': typeof import("../components/HangNhap/DialogCreateDetailHangNhap.vue")['default']
    'LazyHangNhapDialogCreateHangNhap': typeof import("../components/HangNhap/DialogCreateHangNhap.vue")['default']
    'LazyHangNhapDialogEditDetailHangNhap': typeof import("../components/HangNhap/DialogEditDetailHangNhap.vue")['default']
    'LazyHangNhapDialogEditHangNhap': typeof import("../components/HangNhap/DialogEditHangNhap.vue")['default']
    'LazyKhachHangDialogCreateDetailKhachHang': typeof import("../components/KhachHang/DialogCreateDetailKhachHang.vue")['default']
    'LazyKhachHangDialogCreateKhachHang': typeof import("../components/KhachHang/DialogCreateKhachHang.vue")['default']
    'LazyKhachHangDialogEditDetailKhachHang': typeof import("../components/KhachHang/DialogEditDetailKhachHang.vue")['default']
    'LazyKhachHangDialogEditKhachHang': typeof import("../components/KhachHang/DialogEditKhachHang.vue")['default']
    'LazyKhachHangDialogShowInfoKhachHang': typeof import("../components/KhachHang/DialogShowInfoKhachHang.vue")['default']
    'LazyKhachHangDialogShowPrintKhachHang': typeof import("../components/KhachHang/DialogShowPrintKhachHang.vue")['default']
    'LazyKhoHangDialogCreateKhoHang': typeof import("../components/KhoHang/DialogCreateKhoHang.vue")['default']
    'LazyKhoHangDialogEditKhoHang': typeof import("../components/KhoHang/DialogEditKhoHang.vue")['default']
    'LazyLoaiHangDialogCreateLoaiHang': typeof import("../components/LoaiHang/DialogCreateLoaiHang.vue")['default']
    'LazyLoaiHangDialogEditLoaiHang': typeof import("../components/LoaiHang/DialogEditLoaiHang.vue")['default']
    'LazyNhanVienDialogCreateKhachHang': typeof import("../components/NhanVien/DialogCreateKhachHang.vue")['default']
    'LazyNhanVienDialogEditKhachHang': typeof import("../components/NhanVien/DialogEditKhachHang.vue")['default']
    'LazyTrangChuTongDuNo': typeof import("../components/TrangChu/TongDuNo.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyLCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LazyLCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LazyLControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LazyLControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LazyLControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LazyLControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LazyLControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LazyLFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LazyLGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LazyLIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LazyLImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LazyLLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LazyLMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LazyLMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LazyLPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LazyLPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LazyLPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LazyLRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LazyLTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LazyLTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LazyLWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'LazyMglMap': typeof import("@indoorequal/vue-maplibre-gl")['MglMap']
    'LazyMglAttributionControl': typeof import("@indoorequal/vue-maplibre-gl")['MglAttributionControl']
    'LazyMglCustomControl': typeof import("@indoorequal/vue-maplibre-gl")['MglCustomControl']
    'LazyMglFullscreenControl': typeof import("@indoorequal/vue-maplibre-gl")['MglFullscreenControl']
    'LazyMglGeolocateControl': typeof import("@indoorequal/vue-maplibre-gl")['MglGeolocateControl']
    'LazyMglNavigationControl': typeof import("@indoorequal/vue-maplibre-gl")['MglNavigationControl']
    'LazyMglScaleControl': typeof import("@indoorequal/vue-maplibre-gl")['MglScaleControl']
    'LazyMglLogoControl': typeof import("@indoorequal/vue-maplibre-gl")['MglLogoControl']
    'LazyMglMarker': typeof import("@indoorequal/vue-maplibre-gl")['MglMarker']
    'LazyMglPopup': typeof import("@indoorequal/vue-maplibre-gl")['MglPopup']
    'LazyMglCanvasSource': typeof import("@indoorequal/vue-maplibre-gl")['MglCanvasSource']
    'LazyMglGeoJsonSource': typeof import("@indoorequal/vue-maplibre-gl")['MglGeoJsonSource']
    'LazyMglImageSource': typeof import("@indoorequal/vue-maplibre-gl")['MglImageSource']
    'LazyMglRasterSource': typeof import("@indoorequal/vue-maplibre-gl")['MglRasterSource']
    'LazyMglRasterDemSource': typeof import("@indoorequal/vue-maplibre-gl")['MglRasterDemSource']
    'LazyMglVectorSource': typeof import("@indoorequal/vue-maplibre-gl")['MglVectorSource']
    'LazyMglVideoSource': typeof import("@indoorequal/vue-maplibre-gl")['MglVideoSource']
    'LazyMglBackgroundLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglBackgroundLayer']
    'LazyMglCircleLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglCircleLayer']
    'LazyMglFillLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglFillLayer']
    'LazyMglFillExtrusionLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglFillExtrusionLayer']
    'LazyMglHeatmapLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglHeatmapLayer']
    'LazyMglHillshadeLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglHillshadeLayer']
    'LazyMglLineLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglLineLayer']
    'LazyMglRasterLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglRasterLayer']
    'LazyMglSymbolLayer': typeof import("@indoorequal/vue-maplibre-gl")['MglSymbolLayer']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const DoanhThu: typeof import("../components/DoanhThu/doanh-thu.vue")['default']
export const HangNhapDialogCreateDetailHangNhap: typeof import("../components/HangNhap/DialogCreateDetailHangNhap.vue")['default']
export const HangNhapDialogCreateHangNhap: typeof import("../components/HangNhap/DialogCreateHangNhap.vue")['default']
export const HangNhapDialogEditDetailHangNhap: typeof import("../components/HangNhap/DialogEditDetailHangNhap.vue")['default']
export const HangNhapDialogEditHangNhap: typeof import("../components/HangNhap/DialogEditHangNhap.vue")['default']
export const KhachHangDialogCreateDetailKhachHang: typeof import("../components/KhachHang/DialogCreateDetailKhachHang.vue")['default']
export const KhachHangDialogCreateKhachHang: typeof import("../components/KhachHang/DialogCreateKhachHang.vue")['default']
export const KhachHangDialogEditDetailKhachHang: typeof import("../components/KhachHang/DialogEditDetailKhachHang.vue")['default']
export const KhachHangDialogEditKhachHang: typeof import("../components/KhachHang/DialogEditKhachHang.vue")['default']
export const KhachHangDialogShowInfoKhachHang: typeof import("../components/KhachHang/DialogShowInfoKhachHang.vue")['default']
export const KhachHangDialogShowPrintKhachHang: typeof import("../components/KhachHang/DialogShowPrintKhachHang.vue")['default']
export const KhoHangDialogCreateKhoHang: typeof import("../components/KhoHang/DialogCreateKhoHang.vue")['default']
export const KhoHangDialogEditKhoHang: typeof import("../components/KhoHang/DialogEditKhoHang.vue")['default']
export const LoaiHangDialogCreateLoaiHang: typeof import("../components/LoaiHang/DialogCreateLoaiHang.vue")['default']
export const LoaiHangDialogEditLoaiHang: typeof import("../components/LoaiHang/DialogEditLoaiHang.vue")['default']
export const NhanVienDialogCreateKhachHang: typeof import("../components/NhanVien/DialogCreateKhachHang.vue")['default']
export const NhanVienDialogEditKhachHang: typeof import("../components/NhanVien/DialogEditKhachHang.vue")['default']
export const TrangChuTongDuNo: typeof import("../components/TrangChu/TongDuNo.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const MglMap: typeof import("@indoorequal/vue-maplibre-gl")['MglMap']
export const MglAttributionControl: typeof import("@indoorequal/vue-maplibre-gl")['MglAttributionControl']
export const MglCustomControl: typeof import("@indoorequal/vue-maplibre-gl")['MglCustomControl']
export const MglFullscreenControl: typeof import("@indoorequal/vue-maplibre-gl")['MglFullscreenControl']
export const MglGeolocateControl: typeof import("@indoorequal/vue-maplibre-gl")['MglGeolocateControl']
export const MglNavigationControl: typeof import("@indoorequal/vue-maplibre-gl")['MglNavigationControl']
export const MglScaleControl: typeof import("@indoorequal/vue-maplibre-gl")['MglScaleControl']
export const MglLogoControl: typeof import("@indoorequal/vue-maplibre-gl")['MglLogoControl']
export const MglMarker: typeof import("@indoorequal/vue-maplibre-gl")['MglMarker']
export const MglPopup: typeof import("@indoorequal/vue-maplibre-gl")['MglPopup']
export const MglCanvasSource: typeof import("@indoorequal/vue-maplibre-gl")['MglCanvasSource']
export const MglGeoJsonSource: typeof import("@indoorequal/vue-maplibre-gl")['MglGeoJsonSource']
export const MglImageSource: typeof import("@indoorequal/vue-maplibre-gl")['MglImageSource']
export const MglRasterSource: typeof import("@indoorequal/vue-maplibre-gl")['MglRasterSource']
export const MglRasterDemSource: typeof import("@indoorequal/vue-maplibre-gl")['MglRasterDemSource']
export const MglVectorSource: typeof import("@indoorequal/vue-maplibre-gl")['MglVectorSource']
export const MglVideoSource: typeof import("@indoorequal/vue-maplibre-gl")['MglVideoSource']
export const MglBackgroundLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglBackgroundLayer']
export const MglCircleLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglCircleLayer']
export const MglFillLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglFillLayer']
export const MglFillExtrusionLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglFillExtrusionLayer']
export const MglHeatmapLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglHeatmapLayer']
export const MglHillshadeLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglHillshadeLayer']
export const MglLineLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglLineLayer']
export const MglRasterLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglRasterLayer']
export const MglSymbolLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglSymbolLayer']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyDoanhThu: typeof import("../components/DoanhThu/doanh-thu.vue")['default']
export const LazyHangNhapDialogCreateDetailHangNhap: typeof import("../components/HangNhap/DialogCreateDetailHangNhap.vue")['default']
export const LazyHangNhapDialogCreateHangNhap: typeof import("../components/HangNhap/DialogCreateHangNhap.vue")['default']
export const LazyHangNhapDialogEditDetailHangNhap: typeof import("../components/HangNhap/DialogEditDetailHangNhap.vue")['default']
export const LazyHangNhapDialogEditHangNhap: typeof import("../components/HangNhap/DialogEditHangNhap.vue")['default']
export const LazyKhachHangDialogCreateDetailKhachHang: typeof import("../components/KhachHang/DialogCreateDetailKhachHang.vue")['default']
export const LazyKhachHangDialogCreateKhachHang: typeof import("../components/KhachHang/DialogCreateKhachHang.vue")['default']
export const LazyKhachHangDialogEditDetailKhachHang: typeof import("../components/KhachHang/DialogEditDetailKhachHang.vue")['default']
export const LazyKhachHangDialogEditKhachHang: typeof import("../components/KhachHang/DialogEditKhachHang.vue")['default']
export const LazyKhachHangDialogShowInfoKhachHang: typeof import("../components/KhachHang/DialogShowInfoKhachHang.vue")['default']
export const LazyKhachHangDialogShowPrintKhachHang: typeof import("../components/KhachHang/DialogShowPrintKhachHang.vue")['default']
export const LazyKhoHangDialogCreateKhoHang: typeof import("../components/KhoHang/DialogCreateKhoHang.vue")['default']
export const LazyKhoHangDialogEditKhoHang: typeof import("../components/KhoHang/DialogEditKhoHang.vue")['default']
export const LazyLoaiHangDialogCreateLoaiHang: typeof import("../components/LoaiHang/DialogCreateLoaiHang.vue")['default']
export const LazyLoaiHangDialogEditLoaiHang: typeof import("../components/LoaiHang/DialogEditLoaiHang.vue")['default']
export const LazyNhanVienDialogCreateKhachHang: typeof import("../components/NhanVien/DialogCreateKhachHang.vue")['default']
export const LazyNhanVienDialogEditKhachHang: typeof import("../components/NhanVien/DialogEditKhachHang.vue")['default']
export const LazyTrangChuTongDuNo: typeof import("../components/TrangChu/TongDuNo.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyLCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LazyLCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LazyLControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LazyLControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LazyLControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LazyLControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LazyLControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LazyLFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LazyLGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LazyLIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LazyLImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LazyLLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LazyLMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LazyLMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LazyLPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LazyLPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LazyLPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LazyLRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LazyLTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LazyLTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LazyLWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const LazyMglMap: typeof import("@indoorequal/vue-maplibre-gl")['MglMap']
export const LazyMglAttributionControl: typeof import("@indoorequal/vue-maplibre-gl")['MglAttributionControl']
export const LazyMglCustomControl: typeof import("@indoorequal/vue-maplibre-gl")['MglCustomControl']
export const LazyMglFullscreenControl: typeof import("@indoorequal/vue-maplibre-gl")['MglFullscreenControl']
export const LazyMglGeolocateControl: typeof import("@indoorequal/vue-maplibre-gl")['MglGeolocateControl']
export const LazyMglNavigationControl: typeof import("@indoorequal/vue-maplibre-gl")['MglNavigationControl']
export const LazyMglScaleControl: typeof import("@indoorequal/vue-maplibre-gl")['MglScaleControl']
export const LazyMglLogoControl: typeof import("@indoorequal/vue-maplibre-gl")['MglLogoControl']
export const LazyMglMarker: typeof import("@indoorequal/vue-maplibre-gl")['MglMarker']
export const LazyMglPopup: typeof import("@indoorequal/vue-maplibre-gl")['MglPopup']
export const LazyMglCanvasSource: typeof import("@indoorequal/vue-maplibre-gl")['MglCanvasSource']
export const LazyMglGeoJsonSource: typeof import("@indoorequal/vue-maplibre-gl")['MglGeoJsonSource']
export const LazyMglImageSource: typeof import("@indoorequal/vue-maplibre-gl")['MglImageSource']
export const LazyMglRasterSource: typeof import("@indoorequal/vue-maplibre-gl")['MglRasterSource']
export const LazyMglRasterDemSource: typeof import("@indoorequal/vue-maplibre-gl")['MglRasterDemSource']
export const LazyMglVectorSource: typeof import("@indoorequal/vue-maplibre-gl")['MglVectorSource']
export const LazyMglVideoSource: typeof import("@indoorequal/vue-maplibre-gl")['MglVideoSource']
export const LazyMglBackgroundLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglBackgroundLayer']
export const LazyMglCircleLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglCircleLayer']
export const LazyMglFillLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglFillLayer']
export const LazyMglFillExtrusionLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglFillExtrusionLayer']
export const LazyMglHeatmapLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglHeatmapLayer']
export const LazyMglHillshadeLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglHillshadeLayer']
export const LazyMglLineLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglLineLayer']
export const LazyMglRasterLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglRasterLayer']
export const LazyMglSymbolLayer: typeof import("@indoorequal/vue-maplibre-gl")['MglSymbolLayer']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
