// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/7/2025, 11:08:33 PM
const configMerger = require("D:/Download/QLXX Web/qlxx-fe/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/Download/QLXX Web/qlxx-fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/plugins/**/*.{js,ts,mjs}","D:/Download/QLXX Web/qlxx-fe/composables/**/*.{js,ts,mjs}","D:/Download/QLXX Web/qlxx-fe/utils/**/*.{js,ts,mjs}","D:/Download/QLXX Web/qlxx-fe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Download/QLXX Web/qlxx-fe/app.config.{js,ts,mjs}"] } }));

module.exports = config
